### PR TITLE
spline #616 Environment variables naming

### LINKED ISSUE #616: Environment variables naming
## Describe the bug
Hi team, thanks a lot for this project! We are trying this out in a production setting :)

Not really a bug but I thought this was the best place anyway. Your compose uses variables like `spline.database.connectionUrl`, directly mapping to the webenv variables. Not really convention-friendly i.e. `VARIABLE`; Among other things, this is also an issue on some provisioners, such as Azure Container Instances - deploying is not possible because the naming convention - [enforced](https://docs.microsoft.com/en-us/azure/container-instances/container-instances-troubleshooting#naming-conventions) by ACI - prevents it. So something like a wrapper var `SPLINE_DATABASE_CONNECTION_URL` could help.

Thanks,

cc @patrickdehoon

### PR DESCRIPTION
**Pull request by wajda**
Fixes #616

### CODE REVIEW

File: commons/src/main/scala/za/co/absa/spline/common/config/UpperCaseEnvironmentConfiguration.scala [hunk 1]
```diff
@@ -0,0 +1,32 @@
...
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+package za.co.absa.spline.common.config
+
+import org.apache.commons.configuration.EnvironmentConfiguration
+import org.apache.commons.lang.StringUtils
+
+class UpperCaseEnvironmentConfiguration extends EnvironmentConfiguration {
```
Comment (cerveada) [inline commons/src/main/scala/za/co/absa/spline/common/config/UpperCaseEnvironmentConfiguration.scala]:
```suggestion
class NotationInsensitiveEnvironmentConfiguration extends EnvironmentConfiguration {
```

Comment (wajda) [reply commons/src/main/scala/za/co/absa/spline/common/config/UpperCaseEnvironmentConfiguration.scala]: I have even better idea - spit the responsibility. I can make this class only doing UPPER_SNAKE_NOTATION, and instead of calling the `super` method for the fallback add another `EnvironmentConfiguration` instance to the default config resolver stack

Comment (cerveada) [reply commons/src/main/scala/za/co/absa/spline/common/config/UpperCaseEnvironmentConfiguration.scala]: `UPPER_SNAKE_NOTATION` interesting 🐍 😄
