### PR TITLE
spline #1053 Fix warnings

### LINKED ISSUE #1053: Fix compilation warnings
- [x] [WARNING] /home/wajda/Projects/spline/commons/src/main/scala/za/co/absa/spline/common/JsonPath.scala:37: non-variable type argument String in type pattern scala.collection.immutable.Map[String,_] (the underlying of Map[String,_]) is unchecked since it is eliminated by erasure
- [x] [WARNING] /home/wajda/Projects/spline/commons/src/main/scala/za/co/absa/spline/common/JsonPath.scala:38: non-variable type argument String in type pattern java.util.Map[String,_] is unchecked since it is eliminated by erasure
- [x] [WARNING] /home/wajda/Projects/spline/commons/src/main/scala/za/co/absa/spline/common/JsonPath.scala:52: non-variable type argument String in type pattern scala.collection.immutable.Map[String,Any] (the underlying of Map[String,Any]) is unchecked since it is eliminated by erasure
- [x] [WARNING] /home/wajda/Projects/spline/commons/src/main/scala/za/co/absa/spline/common/JsonPath.scala:53: non-variable type argument String in type pattern java.util.Map[String,Any] is unchecked since it is eliminated by erasure
- [x] [WARNING] /home/wajda/Projects/spline/commons/src/main/scala/za/co/absa/spline/common/webmvc/ScalaFutureMethodReturnValueHandler.scala:54: abstract type pattern ScalaFutureMethodReturnValueHandler.this.F is unchecked since it is eliminated by erasure
- [x] [WARNING] /home/wajda/Projects/spline/commons/src/main/scala/za/co/absa/spline/common/webmvc/ScalaFutureMethodReturnValueHandler.scala:54: The outer reference in this type test cannot be checked at run time.

- [x] [WARNING] /home/wajda/Projects/spline/persistence/src/test/scala/com/arangodb/model/ImplicitsSpec.scala:30: class SkiplistIndexOptions in package model is deprecated
- [x] [WARNING] /home/wajda/Projects/spline/persistence/src/test/scala/com/arangodb/model/ImplicitsSpec.scala:34: class HashIndexOptions in package model is deprecated

- [x] [WARNING] /home/wajda/Projects/spline/producer-services/src/main/scala/za/co/absa/spline/producer/service/model/ExecutionPlanPersistentModelBuilder.scala:291: non-variable type argument String in type pattern scala.collection.immutable.Map[String,_] (the underlying of Map[String,_]) is unchecked since it is eliminated by erasure
- [x] [WARNING] /home/wajda/Projects/spline/producer-services/src/main/scala/za/co/absa/spline/producer/service/repo/ExecutionPlanDeserFixAspect.scala:100: non-variable type argument String in type pattern scala.collection.immutable.Map[String,_] (the underlying of Map[String,_]) is unchecked since it is eliminated by erasure
- [x] [WARNING] /home/wajda/Projects/spline/producer-services/src/main/scala/za/co/absa/spline/producer/service/model/ExecutionPlanPersistentModelBuilder.scala:239: match may not be exhaustive.
It would fail on the following input: AttrOrExprRef(None, None)

- [x] [WARNING] /home/wajda/Projects/spline/producer-model-mapper/src/main/scala/za/co/absa/spline/producer/modelmapper/v1_0/spark/AttributeRefConverter.scala:33: non-variable type argument String in type pattern scala.collection.immutable.Map[String,Any] (the underlying of za.co.absa.spline.producer.modelmapper.v1_0.TypesV10.ExprDef) is unchecked since it is eliminated by erasure
- [x] [WARNING] /home/wajda/Projects/spline/producer-model-mapper/src/main/scala/za/co/absa/spline/producer/modelmapper/v1_0/spark/SparkSplineExpressionConverter.scala:32: non-variable type argument String in type pattern scala.collection.immutable.Map[String,Any] (the underlying of za.co.absa.spline.producer.modelmapper.v1_0.TypesV10.ExprDef) is unchecked since it is eliminated by erasure
- [x] [WARNING] /home/wajda/Projects/spline/producer-model-mapper/src/main/scala/za/co/absa/spline/producer/modelmapper/v1_0/spark/SparkSplineObjectConverter.scala:28: non-variable type argument String in type pattern scala.collection.immutable.Map[String,Any] (the underlying of za.co.absa.spline.producer.modelmapper.v1_0.TypesV10.AttrDef) is unchecked since it is eliminated by erasure
- [x] [WARNING] /home/wajda/Projects/spline/producer-model-mapper/src/main/scala/za/co/absa/spline/producer/modelmapper/v1_0/spark/SparkSplineObjectConverter.scala:29: non-variable type argument String in type pattern scala.collection.immutable.Map[String,Any] (the underlying of za.co.absa.spline.producer.modelmapper.v1_0.TypesV10.ExprDef) is unchecked since it is eliminated by erasure

- [x] [WARNING] /home/wajda/Projects/spline/admin/src/main/scala/za/co/absa/spline/admin/AdminCLI.scala:106: match may not be exhaustive.
It would fail on the following inputs: (_, AdminCLIConfig(DBExec(_, _), _, _)), (_, AdminCLIConfig(DBUpgrade(_), _, _))
- [x] [WARNING] /home/wajda/Projects/spline/admin/src/main/scala/za/co/absa/spline/admin/AdminCLI.scala:109: match may not be exhaustive.
It would fail on the following inputs: (_, AdminCLIConfig(DBExec(_, _), _, _)), (_, AdminCLIConfig(DBUpgrade(_), _, _))
- [x] [WARNING] /home/wajda/Projects/spline/admin/src/main/scala/za/co/absa/spline/admin/AdminCLI.scala:128: match may not be exhaustive.
It would fail on the following inputs: (_, AdminCLIConfig(DBInit(_, _, _), _, _)), (_, AdminCLIConfig(DBUpgrade(_), _, _))
- [x] [WARNING] /home/wajda/Projects/spline/admin/src/main/scala/za/co/absa/spline/admin/AdminCLI.scala:131: match may not be exhaustive.
It would fail on the following inputs: (_, AdminCLIConfig(DBInit(_, _, _), _, _)), (_, AdminCLIConfig(DBUpgrade(_), _, _))
- [x] [WARNING] /home/wajda/Projects/spline/admin/src/main/scala/za/co/absa/spline/admin/AdminCLI.scala:134: match may not be exhaustive.
It would fail on the following inputs: (_, AdminCLIConfig(DBInit(_, _, _), _, _)), (_, AdminCLIConfig(DBUpgrade(_), _, _))
- [x] [WARNING] /home/wajda/Projects/spline/admin/src/main/scala/za/co/absa/spline/admin/AdminCLI.scala:137: match may not be exhaustive.
It would fail on the following inputs: (_, AdminCLIConfig(DBInit(_, _, _), _, _)), (_, AdminCLIConfig(DBUpgrade(_), _, _))
- [x] [WARNING] /home/wajda/Projects/spline/admin/src/main/scala/za/co/absa/spline/admin/AdminCLI.scala:140: match may not be exhaustive.
It would fail on the following inputs: (_, AdminCLIConfig(DBInit(_, _, _), _, _)), (_, AdminCLIConfig(DBUpgrade(_), _, _))
- [x] [WARNING] /home/wajda/Projects/spline/admin/src/main/scala/za/co/absa/spline/admin/AdminCLI.scala:143: match may not be exhaustive.
It would fail on the following inputs: (_, AdminCLIConfig(DBInit(_, _, _), _, _)), (_, AdminCLIConfig(DBUpgrade(_), _, _))
- [x] [WARNING] /home/wajda/Projects/spline/admin/src/main/scala/za/co/absa/spline/admin/AdminCLI.scala:146: match may not be exhaustive.
It would fail on the following inputs: (_, AdminCLIConfig(DBInit(_, _, _), _, _)), (_, AdminCLIConfig(DBUpgrade(_), _, _))
- [x] [WARNING] /home/wajda/Projects/spline/admin/src/main/scala/za/co/absa/spline/admin/AdminCLI.scala:149: match may not be exhaustive.
It would fail on the following inputs: (_, AdminCLIConfig(DBInit(_, _, _), _, _)), (_, AdminCLIConfig(DBUpgrade(_), _, _))
- [x] [WARNING] /home/wajda/Projects/spline/admin/src/main/scala/za/co/absa/spline/admin/AdminCLI.scala:178: match may not be exhaustive.
It would fail on the following input: (true, true)

- [x] [WARNING] /home/wajda/Projects/spline/test-data-generator/src/main/scala/za/co/absa/spline/testdatagen/GenCLI.scala:30: Adaptation of argument list by inserting () is deprecated: this is unlikely to be what you want.
        signature: Right.apply[A, B](value: B): scala.util.Right[A,B]
  given arguments: <none>
 after adaptation: Right((): Unit)
- [x] [WARNING] /home/wajda/Projects/spline/test-data-generator/src/main/scala/za/co/absa/spline/testdatagen/GenCLI.scala:41: Adaptation of argument list by inserting () is deprecated: this is unlikely to be what you want.
        signature: Right.apply[A, B](value: B): scala.util.Right[A,B]
  given arguments: <none>
 after adaptation: Right((): Unit)

### PR DESCRIPTION
**Pull request by wajda**
fix some warnings

### CODE REVIEW

File: commons/src/main/scala/za/co/absa/spline/common/JsonPath.scala [hunk 1]
```diff
@@ -49,8 +49,8 @@ class JsonPath(tokens: Seq[Token]) {
         xs2
       }) -> xs.get(i)
 
-      case ((prevSetter: Setter, m: Map[String, Any]), k: String) => prevSetter.compose(m.updated(k, _: Value)) -> m(k)
-      case ((prevSetter: Setter, m: ju.Map[String, Any]), k: String) => prevSetter.compose((v2: Value) => {
+      case ((prevSetter: Setter, m: Map[String@unchecked, _]), k: String) => prevSetter.compose(m.updated(k, _: Value)) -> m(k)
+      case ((prevSetter: Setter, m: ju.Map[String@unchecked, _]), k: String) => prevSetter.compose((v2: Value) => {
         val m2 = new ju.HashMap[String, Any](m)
```
Comment (cerveada) [inline commons/src/main/scala/za/co/absa/spline/common/JsonPath.scala:54]: Shouldn't there be a space?
`String @unchecked`?
I haven't found any hints in the Scala style guide, but seems to me others use space there.

Comment (wajda) [reply commons/src/main/scala/za/co/absa/spline/common/JsonPath.scala:54]: I'm not sure, but this is what IDEA code formatter suggested.

**Review by cerveada — APPROVED** [review]
