### PR TITLE
Bugfix/spline 1122 labels not working

### LINKED ISSUE #1122: Label filter not working
```
18:27:01.244 [http-nio-8080-exec-2] ERROR za.co.absa.commons.error.ErrorRef - ERROR_ID [b82616a2-b274-4937-992a-d53f9cdb4331] Query execution failed: 
================================================================================
WITH progress_view
FOR ee IN progress_view
    SEARCH ee._created <= @asAtTime
        AND (@timestampStart == null OR IN_RANGE(ee.timestamp, @timestampStart, @timestampEnd, true, true))
        AND (@applicationId == null OR @applicationId == ee.extra.appId)
        AND (@dataSourceUri == null OR @dataSourceUri == ee.execPlanDetails.dataSourceUri)
        AND (@writeAppends  == null OR ee.execPlanDetails.append IN @writeAppends)
          AND @lblValues[0] ANY == ee.labels['tags']
        AND (@searchTerm == null
            OR ANALYZER(LIKE(ee.execPlanDetails.frameworkName, CONCAT("%", TOKENS(@searchTerm, "norm_en")[0], "%")), "norm_en")
      OR ANALYZER(LIKE(ee.execPlanDetails.applicationName, CONCAT("%", TOKENS(@searchTerm, "norm_en")[0], "%")), "norm_en")
      OR ANALYZER(LIKE(ee.extra.appId, CONCAT("%", TOKENS(@searchTerm, "norm_en")[0], "%")), "norm_en")
      OR ANALYZER(LIKE(ee.execPlanDetails.dataSourceUri, CONCAT("%", TOKENS(@searchTerm, "norm_en")[0], "%")), "norm_en")
      OR ANALYZER(LIKE(ee.execPlanDetails.dataSourceType, CONCAT("%", TOKENS(@searchTerm, "norm_en")[0], "%")), "norm_en")
        )

    LET resItem = {
        "executionEventId" : ee._key,
        "executionPlanId"  : ee.execPlanDetails.executionPlanKey,
        "frameworkName"    : ee.execPlanDetails.frameworkName,
        "applicationName"  : ee.execPlanDetails.applicationName,
        "applicationId"    : ee.extra.appId,
        "timestamp"        : ee.timestamp,
        "dataSourceName"   : ee.execPlanDetails.dataSourceName,
        "dataSourceUri"    : ee.execPlanDetails.dataSourceUri,
        "dataSourceType"   : ee.execPlanDetails.dataSourceType,
        "append"           : ee.execPlanDetails.append,
        "durationNs"       : ee.durationNs,
        "error"            : ee.error
    }

    SORT resItem.@sortField @sortOrder
    LIMIT @pageOffset*@pageSize, @pageSize

    RETURN resItem
================================================================================
za.co.absa.spline.persistence.DatabaseException: Query execution failed: 
================================================================================
WITH progress_view
FOR ee IN progress_view
    SEARCH ee._created <= @asAtTime
        AND (@timestampStart == null OR IN_RANGE(ee.timestamp, @timestampStart, @timestampEnd, true, true))
        AND (@applicationId == null OR @applicationId == ee.extra.appId)
        AND (@dataSourceUri == null OR @dataSourceUri == ee.execPlanDetails.dataSourceUri)
        AND (@writeAppends  == null OR ee.execPlanDetails.append IN @writeAppends)
          AND @lblValues[0] ANY == ee.labels['tags']
        AND (@searchTerm == null
            OR ANALYZER(LIKE(ee.execPlanDetails.frameworkName, CONCAT("%", TOKENS(@searchTerm, "norm_en")[0], "%")), "norm_en")
      OR ANALYZER(LIKE(ee.execPlanDetails.applicationName, CONCAT("%", TOKENS(@searchTerm, "norm_en")[0], "%")), "norm_en")
      OR ANALYZER(LIKE(ee.extra.appId, CONCAT("%", TOKENS(@searchTerm, "norm_en")[0], "%")), "norm_en")
      OR ANALYZER(LIKE(ee.execPlanDetails.dataSourceUri, CONCAT("%", TOKENS(@searchTerm, "norm_en")[0], "%")), "norm_en")
      OR ANALYZER(LIKE(ee.execPlanDetails.dataSourceType, CONCAT("%", TOKENS(@searchTerm, "norm_en")[0], "%")), "norm_en")
        )

    LET resItem = {
        "executionEventId" : ee._key,
        "executionPlanId"  : ee.execPlanDetails.executionPlanKey,
        "frameworkName"    : ee.execPlanDetails.frameworkName,
        "applicationName"  : ee.execPlanDetails.applicationName,
        "applicationId"    : ee.extra.appId,
        "timestamp"        : ee.timestamp,
        "dataSourceName"   : ee.execPlanDetails.dataSourceName,
        "dataSourceUri"    : ee.execPlanDetails.dataSourceUri,
        "dataSourceType"   : ee.execPlanDetails.dataSourceType,
        "append"           : ee.execPlanDetails.append,
        "durationNs"       : ee.durationNs,
        "error"            : ee.error
    }

    SORT resItem.@sortField @sortOrder
    LIMIT @pageOffset*@pageSize, @pageSize

    RETURN resItem
================================================================================
	at za.co.absa.spline.persistence.ArangoImplicits$ArangoDatabaseAsyncScalaWrapper$$anonfun$queryAs$1.applyOrElse(ArangoImplicits.scala:91)
	at za.co.absa.spline.persistence.ArangoImplicits$ArangoDatabaseAsyncScalaWrapper$$anonfun$queryAs$1.applyOrElse(ArangoImplicits.scala:88)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
	at scala.util.Failure.recover(Try.scala:234)
	at scala.concurrent.Future.$anonfun$recover$1(Future.scala:395)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run$$$capture(Promise.scala:64)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec$$$capture(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: com.arangodb.ArangoDBException: Response: 400, Error: 10 - AQL: failed to build filter while querying arangosearch view, query '{"type":"n-ary or","typeID":63,"subNodes":[{"type":"n-ary and","typeID":62,"subNodes":[{"type":"compare <=","typeID":28,"excludesNull":false,"subNodes":[{"type":"attribute access","typeID":35,"name":"_created","subNodes":[{"type":"reference","typeID":45,"name":"ee","id":0}]},{"type":"value","typeID":40,"value":1667496421180,"vType":"int","vTypeID":2}]},{"type":"value","typeID":40,"value":true,"vType":"bool","vTypeID":1},{"type":"value","typeID":40,"value":true,"vType":"bool","vTypeID":1},{"type":"value","typeID":40,"value":true,"vType":"bool","vTypeID":1},{"type":"value","typeID":40,"value":true,"vType":"bool","vTypeID":1},{"type":"value","typeID":40,"value":true,"vType":"bool","vTypeID":1},{"type":"array compare ==","typeID":65,"subNodes":[{"type":"indexed access","typeID":37,"subNodes":[{"type":"object","typeID":42,"subNodes":[{"type":"object element","typeID":43,"name":"array","subNodes":[{"type":"array","typeID":41,"sorted":false,"subNodes":[{"type":"array","typeID":41,"sorted":false,"subNodes":[{"type":"value","typeID":40,"value":"beer","vType":"string","vTypeID":4}]}]}]}]},{"type":"value","typeID":40,"value":0,"vType":"int","vTypeID":2}]},{"type":"attribute access","typeID":35,"name":"tags","subNodes":[{"type":"attribute access","typeID":35,"name":"labels","subNodes":[{"type":"reference","typeID":45,"name":"ee","id":0}]}]},{"type":"quantifier","typeID":73,"quantifier":"any"}]}]}]}': wrong value node type for Array comparison operator (while executing)
	at com.arangodb.internal.util.ResponseUtils.checkError(ResponseUtils.java:55)
	at com.arangodb.internal.velocystream.VstCommunication.checkError(VstCommunication.java:157)
	at com.arangodb.async.internal.velocystream.VstCommunicationAsync.lambda$execute$1(VstCommunicationAsync.java:80)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
	at com.arangodb.async.internal.velocystream.VstConnectionAsync.lambda$write$0(VstConnectionAsync.java:51)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at com.arangodb.internal.velocystream.internal.MessageStore.consume(MessageStore.java:62)
	at com.arangodb.internal.velocystream.internal.ChunkStore.checkCompleteness(ChunkStore.java:65)
	at com.arangodb.internal.velocystream.internal.ChunkStore.checkCompleteness(ChunkStore.java:59)
	at com.arangodb.internal.velocystream.internal.VstConnection.lambda$open$0(VstConnection.java:218)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

### PR DESCRIPTION
**Pull request by wajda**
fixes #1122 

The problem was in the incorrect serialization of `bindVars` to VPack. Specifically the `lblValues:Array[Array[String]] -> Seq[...] -> Java -> VPack`. The fix was to eliminate unnecessary conversions, and only pass `Array[Array[String]]` types to VPack that do not require Scala to Java conversion and is properly supported.

1. Fixed the `bindVars` serialization
2. Updated commons to the latest 1.3.0
3. Fixed some deprecation warnings

### CODE REVIEW

File: persistence/src/main/scala/za/co/absa/spline/persistence/ArangoConnectionURL.scala [hunk 1]
```diff
@@ -17,23 +17,24 @@
...
+  import za.co.absa.commons.lang.extensions.StringExtension._
 
   require(user.isDefined || password.isEmpty, "user cannot be blank if password is specified")
 
   def asString: String = {
     val userInfo = trimToNull(Seq(user, password.map(_ => "*****")).flatten.mkString(":"))
     val commaSeparatedHostsString = hosts.map { case (host, port) => s"$host:$port" }.mkString(",")
 
-    new StringBuilder()
+    new mutable.StringBuilder()
```
Comment (cerveada) [inline persistence/src/main/scala/za/co/absa/spline/persistence/ArangoConnectionURL.scala:37]: Isn't it the same Class?

**Review by cerveada — APPROVED** [review]

File: persistence/src/main/scala/za/co/absa/spline/persistence/ArangoConnectionURL.scala (hunk 1 above)
Comment (wajda) [reply persistence/src/main/scala/za/co/absa/spline/persistence/ArangoConnectionURL.scala:37]: It is - `scala.collection.mutable.StringBuilder`
Scala guide recommends to explicitly use `mutable` package name to clearly distinguish between mutable and immutable classes.
